spring:
  application:
    name: cultural-facility-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.143.177:3306/ankang_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: XSP1314np!
# ======== MybatisPlus配置 ========
mybatis-plus:

  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*xml
  # 配置驼峰
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射。默认值：true
    map-underscore-to-camel-case: true
    # 开启 Mybatis 二级缓存，默认为 true。
    cache-enabled: true
    # 日志输出实现。StdOutImpl 标准日志控制台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




# 服务器配置
server:
  port: 5566
  servlet:
    context-path: /api

# Google Places API配置
google:
  places:
    api:
      key: ${GOOGLE_PLACES_API_KEY:AIzaSyC3uLHsQzJ5pdWqfWZXqqgB-27UjziU_3k}
      base-url: https://places.googleapis.com/v1

# 日志配置
logging:
  level:
    org.springframework.web: INFO
    com.example.cultural: INFO
    org.springframework.web.client.RestTemplate: DEBUG  # 调试API请求
